global:
  scrape_interval: 10m

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['body.aicu.life']
    relabel_configs:
      - source_labels: [__param_path]
        regex: "/metrics"
        action: drop


