# Generated by Django 4.2.15 on 2025-03-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type1', models.IntegerField(default=0)),
                ('type2', models.IntegerField(default=0)),
                ('type3', models.IntegerField(default=0)),
                ('type4', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('kiosk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.kioskinfo')),
            ],
        ),
    ]
