# Generated by Django 4.2.15 on 2025-03-26 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_kioskcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskinfo',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='sessioninfo',
            name='kiosk_id',
        ),
        migrations.AddField(
            model_name='bodyresult',
            name='height',
            field=models.FloatField(blank=True, default=170.0, null=True),
        ),
        migrations.AddField(
            model_name='bodyresult',
            name='weight',
            field=models.FloatField(blank=True, default=60.0, null=True),
        ),
        migrations.AddField(
            model_name='kioskinfo',
            name='Org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.organizationinfo'),
        ),
        migrations.AddField(
            model_name='sessioninfo',
            name='kiosk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.kioskinfo', to_field='kiosk_id'),
        ),
        migrations.AlterField(
            model_name='bodyresult',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='FamilyUserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family_member_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('profile_image', models.BooleanField(default=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bodyresult',
            name='family_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.familyuserinfo'),
        ),
        migrations.AddIndex(
            model_name='familyuserinfo',
            index=models.Index(fields=['user'], name='analysis_fa_user_id_4d28e7_idx'),
        ),
    ]
