# Generated by Django 4.2.15 on 2025-03-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_kioskinfo_manager_remove_sessioninfo_kiosk_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioninfo',
            old_name='kiosk',
            new_name='kiosk_id',
        ),
    ]
