# Generated by Django 4.2.15 on 2025-03-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_rename_kiosk_sessioninfo_kiosk_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessioninfo',
            old_name='kiosk_id',
            new_name='kiosk',
        ),
    ]
