# Generated by Django 4.2.15 on 2025-03-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_rename_kiosk_id_sessioninfo_kiosk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kioskcount',
            old_name='kiosk_id',
            new_name='kiosk',
        ),
    ]
